name: project_mini_games
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mole_0.png
    - assets/images/mole_1.png
    - assets/images/mole_2.png
    - assets/images/mole_3.png
    - assets/images/mole_4.png